name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build
      uses: gradle/gradle-build-action@v3.1.0
      with:
        gradle-version: 8.7
        arguments: buildPlugin

    - name: Publish
      uses: gradle/gradle-build-action@v3.1.0
      env:
        PUBLISH_TOKEN: ${{ secrets.JETBRAINS_PUBLISH }}
      with:
        gradle-version: 8.7
        arguments: publishPlugin
