name: Gradle Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/wrapper-action@v3
      with:
        gradle-version: 7.4.0

    - name: Build plugin
      run: ./gradlew buildPlugin
      
    - name: Publish plugin
      run: ./gradlew publishPlugin
